### ISSUE TITLE
UI Update

### ISSUE THREAD

**Issue by VesperAkshay** [sparshg/battleship#10]
**Description:**

We are looking to implement a series of updates to the user interface (UI) to improve overall usability and aesthetic appeal. The primary goals of this UI update are to enhance user engagement, streamline navigation, and ensure consistency across all platforms.

**Objectives:**

1. **Visual Refresh:**
   - Update color schemes to align with current branding guidelines.
   - Redesign key UI components (buttons, forms, icons) for a modern look.

2. **Improved Navigation:**
   - Simplify the main navigation menu for easier access to key features.
   - Introduce breadcrumbs for better orientation within the application.

3. **Responsive Design:**
   - Ensure all UI elements are fully responsive across devices (desktop, tablet, mobile).
   - Optimize layouts for various screen sizes to enhance mobile usability.

**Comment by sparshg** [comment]
Looking for what you come up with, the design is already responsive imo. Also note that you can change the daisyui theme from the tailwind.config.js directly but there is no button to do so currently (#4) 

There are also #5 #6 #7 that relate to UI issues that should be referred
