### ISSUE TITLE
Spelling mistake in the README.md

### ISSUE THREAD

**Issue by arilloid** [sparshg/battleship#18]
Hello @sparshg , 

I have found your project while searching through repositories participating in Hacktoberfest and noticed that there is a small spelling mistake in your README.md.

![image](https://github.com/user-attachments/assets/b24934ad-5138-44cb-9947-061bb0d2bed6)

containArized -> containErized (corrected spelling).

I am looking for an easy first contribution to start off Hacktoberfest, so would greatly appreciate if you assign this issue to me :)

**Comment by sparshg** [comment]
Hi, thanks for this, I have merged the change, although PRs with typo fixes are not really counted in hacktoberfest as per their rules. But its a great place to start, you can look for other easy issues, like #4 to add a dark mode button.
