### ISSUE TITLE
End screen

### ISSUE THREAD

**Issue by sparshg** [sparshg/battleship#5]
Game end screen to be made

**Comment by itsKhadeer** [comment]
do you mean there is no win condition in the game right now? like if I find all the boats of my opponent the game still doesn't end

**Comment by sparshg** [comment]
Correct, we need to detect when match finishes, and provide a restart option

**Comment by itsKhadeer** [comment]
ok great I'd like to work on this, please assign me this issue

**Comment by itsKhadeer** [comment]
@sparshg  I made a pull request #17  can you please review it
