### ISSUE TITLE
Can't join if new game created

### ISSUE THREAD

**Issue by sparshg** [sparshg/battleship#6]
Because the backend registers the player in newly created room, can't join unless player leaves this room.
Don't show join button if in a created room

**Comment by ychavoya** [comment]
Hi, I am interested in working on this issue, I am guessing this section would disappear:

![](https://github.com/user-attachments/assets/8210bfa5-8dd6-465c-9bdb-6d96da8e63b8)

Should it be replaced by something else? Maybe a text specifying that you should provide the code to your opponent so you can start the game, what do you think?

**Comment by sparshg** [comment]
Yep,
I can think of 2 solutions
1. hide join button and show the disconnect button instead of join button? with some share this room code text.
2. The other way is to actually disconnect the player automatically if user has enetered a 4 digit code (not equal to generated room code) when join button is clicked. Then join the room with entered code instead.

Both approaches seem fine to me, you can try implementing the one you like
